# Generated by Django 5.1.2 on 2024-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='artist_name',
            field=models.CharField(max_length=100),
        ),
    ]
