# Generated by Django 5.1.2 on 2024-11-02 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_title', models.CharField(max_length=200)),
                ('art_desc', models.CharField(max_length=200)),
                ('art_image', models.ImageField(upload_to='artworks')),
            ],
        ),
    ]
