# Generated by Django 5.1.2 on 2024-11-02 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='art_desc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='art_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='art_title',
            new_name='title',
        ),
    ]
