# Generated by Django 5.1.2 on 2024-11-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_artwork_created_at_artwork_likes_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
