# Generated by Django 5.1.2 on 2024-11-07 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_alter_artwork_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
