# Generated by Django 5.1.2 on 2024-11-14 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(upload_to='uploads/artworks/'),
        ),
    ]
