# Generated by Django 5.1.2 on 2024-11-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_alter_artwork_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='desc',
            field=models.TextField(max_length=200),
        ),
    ]
