# Generated by Django 5.1.2 on 2024-11-20 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_artwork_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(default='static/profile-pic-placeholder.png', upload_to='uploads/artworks/'),
        ),
    ]
